# config.yaml (defafault config)

experiment:
  name: ".NONE"           # can be set at runtime
  project: "STAGE"        # W&B project
  seed: 42
  device: "cuda:0"
  tags: []                # optional

data:
  dataset: "CIFAR100"
  batch_size: 256
  vision: true

model:
  arch: "FOTON"            # or "PEPITA" etc.
  layers:
    dims: [256, 256]
    bias: false
    activation: "relu"
    init: "orthogonal"
    dropout: 0.1
  ortho:
    rate: 1               # apply every N steps
    t_bjorck: 5           # iterations if using Björck
  error: "CE"             # loss function, "CE" or "MSE"

training:
  epochs: 100
  lr: 0.5
  lr_sched:
    factor: 1
    milestones: [30, 60]
  loss: "cross_entropy"
  ce_T: 1.0             # temperature for cross-entropy
  weight_decay: 0
  update_F: 1
  thresholds:            # early stop conditi0on
    epoch: 500
    test_acc_min: 93.0
    train_acc_min: 95.0

optim:
  name: "sgd"            # or "adam"
  momentum: 0            # set if sgd with momentum is used
  betas: [0.9, 0.999]    # for adam
  eps: 1e-8

foton:
  rule: "FOTON"          # "BPFOTON" etc.
  norm_kernel: null

adversarial:
  attack: null           # "pgd" | "fgsm" | null
  train: false
  test: false
  eps: null
